# CI/CD Pipeline
# Builds app, docker image, and pushes to ECR

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: IMAGE_NAME
    value: helloworld/$(Build.BuildId)
  - name: PUSH_TAG
    value: latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release'
    zipAfterPublish: false
    modifyOutputPath: false

- task: Docker@2
  displayName: Build docker image
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    arguments: '-t $(IMAGE_NAME)'
    tags: |
      latest

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS_ECS'
    regionName: 'us-east-2'
    imageSource: imagename
    sourceImageName: $(IMAGE_NAME)
    repositoryName: 'outsystems_exercise'
    pushTag: $(PUSH_TAG)
