# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: ECS_REPOSITORY
    value: 149091607530.dkr.ecr.us-east-2.amazonaws.com/outsystems_exercise

steps:
- task: Docker@2
  displayName: Build & push docker image
  inputs:
    repository: $(ECS_REPOSITORY)
    command: buildAndPush
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
